"""Generated by scripts/generate_contract.py; do not edit."""

CONTRACT_VERSION = '1.0.0'

CONTRACT_SHA256 = 'b67fceeb7f9c9c207c1cf63585debd7b4adf655f8e5d46acb954a35f36fd0234'

CATALOG_PROTOCOL_VERSION = 1

TRANSPORTS = {'native': {'query_key': 'query',
            'version_key': 'protocol_version',
            'default_limit': 25,
            'max_limit': 50,
            'max_cursor': 10000},
 'legacy_http': {'query_key': 'q',
                 'version_key': 'protocol',
                 'default_limit': 50,
                 'max_limit': 100}}

REQUEST_LIMITS = {'query': 120, 'field': 40, 'area': 120, 'device_id': 120, 'capability': 80}

FIELD_DOMAINS = {'entity': None,
 'state_entity': None,
 'sensor': ['binary_sensor', 'input_number', 'sensor', 'text_sensor'],
 'binary_sensor': ['binary_sensor'],
 'text_sensor': ['text_sensor'],
 'light': ['light'],
 'fan': ['fan'],
 'climate': ['climate'],
 'cover': ['cover'],
 'lock': ['lock'],
 'alarm': ['alarm_control_panel'],
 'media_player': ['media_player'],
 'vacuum': ['vacuum'],
 'lawn_mower': ['lawn_mower'],
 'weather': ['weather'],
 'camera': ['camera', 'image'],
 'select': ['input_select', 'select'],
 'number': ['input_number', 'number'],
 'switch': ['input_boolean', 'switch'],
 'person': ['person'],
 'device_tracker': ['device_tracker'],
 'scene': ['scene'],
 'script': ['script'],
 'automation': ['automation'],
 'button': ['button', 'input_button'],
 'action': ['automation',
            'button',
            'input_boolean',
            'input_button',
            'input_number',
            'input_select',
            'number',
            'scene',
            'script',
            'select']}

METADATA_FIELDS = ('entity_id',
 'domain',
 'device_id',
 'name',
 'device_name',
 'area_name',
 'device_class',
 'icon',
 'unit',
 'available',
 'disabled',
 'hidden',
 'capabilities')
