"""Generate the small, vendorable catalog contract. No HA installation required."""

from __future__ import annotations

import argparse
import hashlib
import json
import pprint
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs() -> dict[Path, str]:
    source = ROOT / "protocol/catalog-v1.json"
    raw = source.read_bytes()
    contract = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()
    constants = {
        "CONTRACT_VERSION": contract["version"],
        "CONTRACT_SHA256": digest,
        "CATALOG_PROTOCOL_VERSION": contract["wire_version"],
        "TRANSPORTS": contract["transports"],
        "REQUEST_LIMITS": contract["request_limits"],
        "FIELD_DOMAINS": contract["field_domains"],
        "METADATA_FIELDS": tuple(contract["metadata"]),
    }
    python = '"""Generated by scripts/generate_contract.py; do not edit."""\n\n'
    python += (
        "\n\n".join(
            f"{key} = {pprint.pformat(value, sort_dicts=False)}"
            for key, value in constants.items()
        )
        + "\n"
    )
    types = []
    for name, kind in contract["metadata"].items():
        types.append(f"    {name}: {kind};")
    ts = "// Generated by scripts/generate_contract.py; do not edit.\n"
    ts += (
        f"export const CATALOG_CONTRACT_VERSION = {json.dumps(contract['version'])};\n"
    )
    ts += f"export const CATALOG_CONTRACT_SHA256 = {json.dumps(digest)};\n"
    ts += f"export const CATALOG_PROTOCOL_VERSION = {contract['wire_version']};\n"
    ts += (
        "export const CATALOG_TRANSPORTS = "
        + json.dumps({"native": contract["transports"]["native"]}, indent=4)
        + " as const;\n"
    )
    ts += (
        "export const CATALOG_FIELD_DOMAINS = "
        + json.dumps(contract["field_domains"], indent=4)
        + " as const;\n"
    )
    ts += (
        "export const CATALOG_PICKER_FIELDS = "
        + json.dumps(contract["picker_domain_fields"], indent=4)
        + " as const;\n"
    )
    ts += (
        "export const CATALOG_PICKER_GROUPS = "
        + json.dumps(contract["picker_group_fields"])
        + " as const;\n"
    )
    ts += "export interface HomeAssistantEntityRecord {\n" + "\n".join(types) + "\n}\n"
    ts += "export interface HomeAssistantEntityPage {\n    protocol_version: number;\n    entities: HomeAssistantEntityRecord[];\n    next_cursor: number | null;\n}\n"
    cpp = "// Generated by scripts/generate_contract.py; do not edit.\n#pragma once\n\nnamespace espcontrol::catalog_contract {\n"
    cpp += f'inline constexpr char VERSION[] = "{contract["version"]}";\n'
    cpp += f'inline constexpr char SHA256[] = "{digest}";\n'
    cpp += f"inline constexpr int PROTOCOL_VERSION = {contract['wire_version']};\n"
    for name, value in contract["transports"]["native"].items():
        if isinstance(value, int):
            cpp += f"inline constexpr int {name.upper()} = {value};\n"
    for name, value in contract["request_limits"].items():
        cpp += f"inline constexpr int MAX_{name.upper()}_LENGTH = {value};\n"
    for name, value in contract["firmware_bridge"].items():
        cpp += f"inline constexpr int {name.upper()} = {value};\n"
    cpp += "}  // namespace espcontrol::catalog_contract\n"
    doc = f"# Catalog contract {contract['version']}\n\nGenerated from `protocol/catalog-v1.json`; edit the source and run `python3 scripts/generate_contract.py`.\n\n"
    doc += f"Wire version: {contract['wire_version']}. SHA-256: `{digest}`.\n\n"
    doc += "## Transport compatibility\n\n| Transport | Query key | Version key | Default page | Maximum page | Cursor maximum |\n|---|---|---|---:|---:|---:|\n"
    for name, transport in contract["transports"].items():
        doc += f"| {name} | {transport['query_key']} | {transport['version_key']} | {transport['default_limit']} | {transport['max_limit']} | {transport.get('max_cursor', 'unbounded')} |\n"
    doc += (
        "\n"
        + contract["pagination"]
        + "\n\n## Selection metadata\n\n| Field | Type |\n|---|---|\n"
    )
    for name, kind in contract["metadata"].items():
        doc += f"| {name} | {kind.replace('|', 'or')} |\n"
    doc += "\nRaw states, arbitrary attributes, camera URLs and credentials are excluded.\n\n## Picker fields\n\n| Field | Accepted HA domains |\n|---|---|\n"
    for name, domains in contract["field_domains"].items():
        doc += f"| {name} | {', '.join(domains) if domains else 'Any (also the fallback for unknown fields)'} |\n"
    return {
        ROOT / "custom_components/espcontrol/catalog_contract.py": python,
        ROOT / "protocol/generated/catalog.ts": ts,
        ROOT / "protocol/generated/catalog.h": cpp,
        ROOT / "docs/catalog-contract.md": doc,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Stale generated contract: " + ", ".join(stale))


if __name__ == "__main__":
    main()
